apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: hello-arc
spec:
  releaseName: hello-arc-prod
  chart:
    git: git@github.com:likamrat/hello_arc
    path: charts/hello-arc
    ref: master
  values:
    image:
      repository: liorkamrat/hello-arc
      tag: latest
    replicaCount: 3
