apiVersion: v1
kind: Service
metadata:
  name: hello-arc-custom
  namespace: hello-arc 
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-arc-custom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-arc-custom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-arc-custom
  template:
    metadata:
      labels:
        app: hello-arc-custom
    spec:
      containers:
      - name: hello-arc
        image: liorkamrat/hello-arc:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: I just deployed this on Kubernetes!
