apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-arc-kind
  namespace: prod
spec:
  releaseName: hello-arc-prod
  chart:
    git: https://github.com/likamrat/hello_arc.git
    path: charts/hello-arc-kind
    ref: master
  values:
    image:
      repository: liorkamrat/hello-arc
      tag: latest
    replicaCount: 1
    env:
      name: MESSAGE
      value: Hello Arc GitOps Demo!
